#!/usr/bin/env bash

# rofi-sway-switch-colorscheme3
#
# Description: change colorscheme of SwayWM theme
# Author: demingongo
# Link: https://github.com/demingongo
# Availability: https://github.com/demingongo/sway-dotfiles

set -e

## init

# script that will change the colorscheme
SWITCHER_CMD="$HOME/.local/bin/sway_switch_theme"

# ini file parser
# https://github.com/demingongo/ini-reader
INI_READER="ini-reader"

# config file path
CONFIG_FILE_PATH=''

# parse options
opts=$(getopt --longoptions=config: --name "$0" --options "" -- "$@")
eval set -- $opts
unset opts

while [[ $# -gt 0 ]]; do
	case "$1" in
		"--config")
            		CONFIG_FILE_PATH="$2"
            		shift 2
            		;;
        	"--")
	  	        shift
	            	break
        		;;
        	*)
			echo "Error $1" >&2
			exit 1
            		;;
    esac
done

# validate options
if [ -z "$CONFIG_FILE_PATH" ]; then
	echo "Missing option: \"--config <path/to/config/file>\"" >&2
	exit 1
fi

## process ini file

theme_name=$("$INI_READER" "$CONFIG_FILE_PATH" main name)
default_icon=$("$INI_READER" "$CONFIG_FILE_PATH" main preview)

if [[ -z "$theme_name" ]]; then
	echo "Missing main.name (theme name) in: \"$CONFIG_FILE_PATH\"" >&2
	exit 1
fi

if [[ -n "$default_icon" ]]; then
	default_icon=$(eval "echo \"$default_icon\"")
fi

declare -A colorschemes
declare -A icons

function load_icons()
{
	local cmd="$INI_READER $CONFIG_FILE_PATH colorschemes_previews"

	while read -r a b; do icons["$a"]="$(eval "echo \"$b\"")"; done < <($cmd)
}

function load_colorschemes()
{
	load_icons
	
	local cmd="$INI_READER $CONFIG_FILE_PATH colorschemes"

	while read -r a b; do colorschemes["$a"]="$b"; done < <($cmd)
}

load_colorschemes

if [ $# -gt 0 ]
then
    # If arguments given, use those as the selection
    selection="${@}"
fi

# Don't allow custom entries
echo -e "\0no-custom\x1ftrue"
# Use markup
echo -e "\0markup-rows\x1ftrue"

if [ -z "${selection+x}" ]
then
    echo -e "\0prompt\x1fSelect a colorscheme"

	if [[ -z "${default_icon}" ]]; then
    	echo -e "default"
	else
		echo -e "default\0icon\x1f${default_icon}"
	fi
    for i in "${!colorschemes[@]}"
    do
		if [[ -z "${icons[$i]}" ]]; then
    		echo -e "${colorschemes[$i]}"
		else
			echo -e "${colorschemes[$i]}\0icon\x1f${icons[$i]}"
		fi
    done
else
    # Change colorscheme
    if [ "$selection" = 'default' ]; then
	    found_scheme='default'
    else
    	for key in "${!colorschemes[@]}"
    	do
		if [ "$selection" = "${colorschemes[$key]}" ]; then
			found_scheme="$key"
			break
		fi
    	done
    fi

    if [ -n "${found_scheme+x}" ]
    then
	    eval "$SWITCHER_CMD $theme_name \"$found_scheme\" --keepbg"
	    exit 0
    fi

    echo "Invalid: $selection" >&2
    exit 1
fi

